server:
  port: 8080

logging:
  level:
    org.springframework: 'DEBUG'


spring:
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          -
            type: git
            uri: ${app.repo.github.uri}
            username: ${app.repo.github.username}
            password: ${app.repo.github.password}
            searchPaths: "*"
          -
            type: vault
            host: ${vault.host}
            port: ${vault.port}
            scheme: https
            backend: ${vault.org}
            profileSeparator: /
            defaultKey: shared-credentials
        vault:
          host: ${vault.host}
          port: ${vault.port}
          scheme: https
          backend: ${vault.org}
          profileSeparator: /
          defaultKey: shared-credentials
          authentication:
            type: APP_ROLE
            appRole:
              roleId: ${vault.roleId}
              secretId: ${vault.secretId}
